### ISSUE TITLE
Optional parameter for max number of votes

### ISSUE THREAD

**Issue by sloane-shark** [kedarv/votey#13]
This would let us do something like `/vote "poll name" "option 1" 1` to limit to a single vote per user, or a higher number if we want to allow a variable but finite number of votes

**Comment by sloane-shark** [comment]
we'd have to look for an optional+unquoted integer at the end, or maybe use some syntax like `/vote ... max=1`?

**Comment by kedarv** [comment]
I think the extra parsing work is worth being able to just specify a number

**Comment by kedarv** [comment]
done!
