### ISSUE TITLE
Can't parse round quotes correctly

### ISSUE THREAD

**Issue by pkfoury** [kedarv/votey#2]
![51569510_805777989774906_6650911846045843456_n](https://user-images.githubusercontent.com/22671016/52252212-25db9680-28cf-11e9-9e4f-be5a3e64895f.png)

Errors come from trying to parse round quotes (“”) instead of block quotes (""). Looks like round quotes are on by default in MacOS spelling correction.

Easy fix is to convert to block quotes before splitting

**Comment by kedarv** [comment]
Adding onto this issue - we should catch parsing errors instead of adding in bad data or crashing - and also make sure to sanitize data

**Comment by kedarv** [comment]
Fixed in https://github.com/kedarv/votey/commit/883fc6aa0ba31dbce08be1cccfa60852c47ba4da
Ticketed up my previous comment in https://github.com/kedarv/votey/issues/3
